### ISSUE TITLE
Cannot display email threads

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#557] opened 2018-09-26 21:18 UTC
An upgrade is affecting astroid recently on Arch. It cannot display email thread views any more. Here's the console output when trying to open a thread view from the thread index:

```
[23:16:13] [0x00007f7bd6b37c40] [M] [debug] mw: set active: 0, current: 0
[23:16:13] [0x00007f7bd6b37c40] [M] [debug] mw: focus-in: 1 active: true, in_quit: false
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ti: open thread: 0000000000032eec (true)
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] theme: loading..
[23:16:14] [0x00007f7bd6b37c40] [M] [info] re: using user configured resource: /home/hugo/ui/thread-view.html
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] tv: testing version: 5
[23:16:14] [0x00007f7bd6b37c40] [M] [info] re: using user configured resource: /home/hugo/ui/thread-view.scss
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] tv: testing version: 5
[23:16:14] [0x00007f7bd6b37c40] [M] [info] re: using user configured resource: /home/hugo/ui/part.scss
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] tv: testing version: 5
[23:16:14] [0x00007f7bd6b37c40] [M] [info] theme: processing: /home/hugo/.config/astroid/ui/thread-view.scss
[23:16:14] [0x00007f7bd6b37c40] [M] [info] theme: processing: /home/hugo/.config/astroid/ui/part.scss
[23:16:14] [0x00007f7bd6b37c40] [M] [info] pc: adding /usr/lib/astroid/web-extensions to web extension search path.
[23:16:14] [0x00007f7bd6b37c40] [M] [warning] pc: id: 1
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] pc: socket: /home/hugo/.cache/astroid/sockets/astroid.12213.1.xlba7urxqmecu0idwlatuy60cnskvm
[23:16:14] [0x00007f7bd6b37c40] [M] [info] render: loading html..
[23:16:14] [0x00007f7bd6b37c40] [M] [info] key: binding unbound target: 
[23:16:14] [0x00007f7bd6b37c40] [M] [warning] key: e (thread_view.edit_draft) already exists in map with name: thread_view.expand, overwriting.
[23:16:14] [0x00007f7bd6b37c40] [M] [info] ky: run, binding: thread_view.run(w) (userdefined: true) to: /home/hugo/.config/astroid/hooks/togglemail waiting %2, 
[23:16:14] [0x00007f7bd6b37c40] [M] [info] ky: run, binding: thread_view.run(C-t) (userdefined: true) to: /home/hugo/.config/astroid/hooks/todocyclemail todo %2, 
[23:16:14] [0x00007f7bd6b37c40] [M] [info] ky: run, binding: thread_view.run(X) (userdefined: true) to: /home/hugo/.config/astroid/hooks/togglemail spam %2, 
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] mw: set active: 1, current: 0
[23:16:14] [0x00007f7bd6b37c40] [M] [info] tv: load thread: 0000000000032eec
[23:16:14] [0x00007f7bd6b37c40] [M] [info] db: open db read-only, waiting for lock..
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] db: read-only got lock.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] db: open time: 0.822 ms.
[23:16:14] [0x00007f7bd6b37c40] [M] [info] msg: loading mid: CAGgihWR0K+r4Phw1wb38hCd=YFPNH3LabfHjq3aBEAojxxAoqg@mail.gmail.com
[23:16:14] [0x00007f7bd6b37c40] [M] [info] msg: filename: /home/hugo/.email/imap/kolab/INBOX/cur/1537992427_2.1388.xps,U=23903,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk (0): content-type: text/plain
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: preferred.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: is part (viewable: true, attachment: false) 
[23:16:14] [0x00007f7bd6b37c40] [M] [info] msg: loading mid: 34652931537978893@iva8-3af116a85b74.qloud-c.yandex.net
[23:16:14] [0x00007f7bd6b37c40] [M] [info] msg: filename: /home/hugo/.email/imap/kolab/INBOX/cur/1537992429_1.1388.xps,U=23905,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk (1): content-type: multipart/mixed
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: multi part
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: alternative: false
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk (2): content-type: text/html
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: is part (viewable: true, attachment: false) 
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk (3): content-type: text/plain
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: preferred.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: is part (viewable: true, attachment: false) 
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: multi part end
[23:16:14] [0x00007f7bd6b37c40] [M] [info] msg: loading mid: 033b01d455cc$e54b8c90$afe2a5b0$@censored
[23:16:14] [0x00007f7bd6b37c40] [M] [info] msg: filename: /home/hugo/.email/imap/kolab/INBOX/cur/1537992430_3.1388.xps,U=23912,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk (4): content-type: multipart/mixed
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: multi part
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: alternative: false
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk (5): content-type: multipart/alternative
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: multi part
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: alternative: true
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk (6): content-type: text/plain
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: preferred.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: is part (viewable: true, attachment: false) 
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk (7): content-type: text/html
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: is part (viewable: true, attachment: false) 
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: multipart: added sibling
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: multipart: preferred.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: multipart: added sibling
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: multi part end
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk (8): content-type: text/plain
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: preferred.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: is part (viewable: true, attachment: false) 
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: multi part end
[23:16:14] [0x00007f7bd6b37c40] [M] [info] msg: loading mid: 77e9fd5f-28db-3b6e-b916-1a7b3c19493b@censored
[23:16:14] [0x00007f7bd6b37c40] [M] [info] msg: filename: /home/hugo/.email/imap/kolab/INBOX/cur/1537996554_0.12220.xps,U=23923,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk (9): content-type: text/plain
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: preferred.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: is part (viewable: true, attachment: false) 
[23:16:14] [0x00007f7bd6b37c40] [M] [info] db: closing db.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] db: ro: waiting for lock to close..
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] db: ro: closing..
[23:16:14] [0x00007f7bd6b37c40] [M] [warning] pc: got extension connect
[2018-09-26 23:16:14.453950] [0x00007ff7b991a700] [debug]   reader thread: started.
[2018-09-26 23:16:14.453966] [0x00007ff7b991a700] [debug]   reader waiting..
[2018-09-26 23:16:14.557530] [0x00007ff823beb3c0] [debug]   page created.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] tv: decide policy
[2018-09-26 23:16:14.571074] [0x00007ff823beb3c0] [debug]   request: /home/hugo/.config/astroid/6byfkbpkvx1c30htfhc2yx93mac88sq98..
[2018-09-26 23:16:14.571094] [0x00007ff823beb3c0] [debug]   request: allow.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] tv: on_load_changed: 0
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] tv: on_load_changed: 2
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] tv: decide policy
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] tv: on_load_changed: 3
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] tv: load finished.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] pc: sending page..
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: sending: Page
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: send (sync) waiting for lock..
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: send (sync) lock acquired.
[2018-09-26 23:16:14.622536] [0x00007ff7b991a700] [debug]   reader waiting..
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: wrote: 34279 of 34279 bytes.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: send (sync) waiting for ACK..
[23:16:14] [0x00007ff823beb3c0] [E] [debug] loading html..
[23:16:14] [0x00007ff823beb3c0] [E] [debug] loading stylesheet..
[23:16:14] [0x00007ff823beb3c0] [E] [debug] done
[23:16:14] [0x00007ff823beb3c0] [E] [debug] ae: sending: Ack
[23:16:14] [0x00007ff823beb3c0] [E] [debug] ae: send (async) waiting for lock
[23:16:14] [0x00007ff823beb3c0] [E] [debug] ae: wrote: 17 of 17 bytes.
[23:16:14] [0x00007ff823beb3c0] [E] [debug] ae: send (async) message sent.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: send (sync) ACK received.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] pc: clear messages..
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: sending: ClearMessages
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: send (sync) waiting for lock..
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: send (sync) lock acquired.
[23:16:14] [0x00007ff7b991a700] [E] [debug] reader waiting..
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: wrote: 2 of 2 bytes.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: send (sync) waiting for ACK..
[23:16:14] [0x00007ff823beb3c0] [E] [debug] clearing all messages.
[23:16:14] [0x00007ff823beb3c0] [E] [debug] ae: sending: Ack
[23:16:14] [0x00007ff823beb3c0] [E] [debug] ae: send (async) waiting for lock
[23:16:14] [0x00007ff823beb3c0] [E] [debug] ae: wrote: 17 of 17 bytes.
[23:16:14] [0x00007ff823beb3c0] [E] [debug] ae: send (async) message sent.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: send (sync) ACK received.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] render: html loaded, building messages..
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] tv: adding message: CAGgihWR0K+r4Phw1wb38hCd=YFPNH3LabfHjq3aBEAojxxAoqg@mail.gmail.com
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] gravatar: for: censored@gmail.com, uri: https://www.gravatar.com/avatar/fd75647d5ecd90bb03f0acensored?d=retro&s=48
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: body: part
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: plain text (out html: false)
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] enc: base64
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] charset: utf-8
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] create message part: 0 (siblings: 0) (kids: 0) (attachment: false) (viewable: true) (mimetype: text/plain)
[23:16:14] [0x00007f7bd6b37c40] [M] [info] chunk: contents: loaded 1140 bytes in 0.027 ms.
[23:16:14] [0x00007f7bd6b37c40] [M] [info] chunk: file size: 1140 (time used to calculate: 0.056 s.)
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: body: part
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: plain text (out html: true)
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] enc: base64
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] charset: utf-8
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: body: part
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] chunk: plain text (out html: false)
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] enc: base64
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] charset: utf-8
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: sending: AddMessage
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: send (sync) waiting for lock..
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: send (sync) lock acquired.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: wrote: 2471 of 2471 bytes.
[23:16:14] [0x00007f7bd6b37c40] [M] [debug] ae: send (sync) waiting for ACK..
[23:16:14] [0x00007ff7b991a700] [E] [debug] reader waiting..
[23:16:14] [0x00007ff823beb3c0] [E] [debug] adding message: CAGgihWR0K+r4Phw1wb38hCd=YFPNH3LabfHjq3aBEAojxxAoqg@mail.gmail.com
[23:16:14] [0x00007ff823beb3c0] [E] [debug] request: https://www.gravatar.com/avatar/fd75647d5ecd90bb03f0a3censoredd8..
[23:16:14] [0x00007ff823beb3c0] [E] [debug] request: allow.
[23:16:14] [0x00007ff823beb3c0] [E] [debug] create message part: 0 (siblings: false) (kids: 0) (attachment: false) (viewable: true) (focusable: false) (mimetype: text/plain)
[23:16:14] [0x00007ff823beb3c0] [E] [debug] create body part: 0

```

**Comment by hugoroy** [comment] 2018-09-26 21:30
Downgrading webkit2gtk to 2.20 did the trick.

**Comment by gauteh** [comment] 2018-09-27 05:42
Probably duplicate of #550. Seems that we might have to do another webkit API port.

**Closed by gauteh** 2018-09-27 05:42 UTC
