### ISSUE TITLE
Feature Request: Archive Thread and Close Threadview

### ISSUE THREAD

**Issue by jackdesert** [astroidmail/astroid#273] opened 2017-02-08 15:26 UTC
I would like a hotkey for "archive this thread and close this threadview"

As it is, I quite often use the combination "a" to archive, followed by "CTRL-w" to close the threadview. I just want to be able to do it with one keypress.

**Comment by gauteh** [comment] 2017-02-12 15:43
Duplicate of #91, very useful feature, haven't found the time to implement it yet.

**Closed by gauteh** 2017-02-12 15:43 UTC
Labels: duplicate, feature-request
