### ISSUE TITLE
Segfault on thread view

### ISSUE THREAD

**Issue by serussell** [astroidmail/astroid#660] opened 2019-09-08 12:50 UTC
Astroid is segfaulting when I try to open (view) a particular thread from the message list.  This is Astroid v 0.15 (92938e5347eb7d93c1ece98a543c06e37cf3161b), built from git on Arch.

I suspect this is related to PGP signed messages; it does not happen on all signed messages.

Here's the log; the email thread (`--format mbox`) is attached.

```
[07:30:36] [0x00007f7415397c00] [M] [debug] mw: set active: 1, current: 1
[07:30:36] [0x00007f7415397c00] [M] [debug] mw: focus-in: 1 active: true,
in_quit: false
[07:30:37] [0x00007f7415397c00] [M] [debug] ti: open thread: 000000000002a138
(true)
[07:30:37] [0x00007f7415397c00] [M] [debug] theme: loading..
[07:30:37] [0x00007f7415397c00] [M] [info] re: using installed resource:
/usr/local/share/astroid/ui/thread-view.html
[07:30:37] [0x00007f7415397c00] [M] [debug] tv: testing version: 5
[07:30:37] [0x00007f7415397c00] [M] [info] re: using user configured resource:
/home/ser/ui/thread-view.scss
[07:30:37] [0x00007f7415397c00] [M] [debug] tv: testing version: 5
[07:30:37] [0x00007f7415397c00] [M] [info] re: using installed resource:
/usr/local/share/astroid/ui/part.scss
[07:30:37] [0x00007f7415397c00] [M] [debug] tv: testing version: 5
[07:30:37] [0x00007f7415397c00] [M] [info] theme: processing:
/home/ser/.config/astroid/ui/thread-view.scss
[07:30:37] [0x00007f7415397c00] [M] [info] theme: processing:
/usr/local/share/astroid/ui/part.scss
[07:30:37] [0x00007f7415397c00] [M] [warning] pc: DEBUG build. no local
extension found. adding installed path.
[07:30:37] [0x00007f7415397c00] [M] [info] pc: adding
/usr/local/lib/astroid/web-extensions to web extension search path.
[07:30:37] [0x00007f7415397c00] [M] [warning] pc: id: 1
[07:30:37] [0x00007f7415397c00] [M] [debug] pc: socket:
/home/ser/.cache/astroid/sockets/astroid.395.1.c1u3j6qfz9b5ky9lxij4c7c3mrzm2a
[07:30:37] [0x00007f7415397c00] [M] [info] render: loading html..
[07:30:37] [0x00007f7415397c00] [M] [info] ky: run, binding:
thread_view.run(C-D) (userdefined: true) to: astroid_decrypt %1,
[07:30:37] [0x00007f7415397c00] [M] [debug] mw: set active: 2, current: 1
[07:30:37] [0x00007f7415397c00] [M] [info] tv: load thread: 000000000002a138
[07:30:37] [0x00007f7415397c00] [M] [info] db: open db read-only, waiting for
lock..
[07:30:37] [0x00007f7415397c00] [M] [debug] db: read-only got lock.
[07:30:37] [0x00007f7415397c00] [M] [debug] db: open time: 0.385 ms.
[07:30:37] [0x00007f7415397c00] [M] [error] db: got more than one thread for
thread id.
[07:30:37] [0x00007f7415397c00] [M] [debug] mt: destruct.
[07:30:37] [0x00007f7415397c00] [M] [info] db: closing db.
[07:30:37] [0x00007f7415397c00] [M] [debug] db: ro: waiting for lock to
close..
[07:30:37] [0x00007f7415397c00] [M] [debug] db: ro: closing..

(astroid:395): glibmm-ERROR **: 07:30:37.683:
unhandled exception (type std::exception) in signal handler:
what: db: got more than one thread for thread id.

[1]    395 trace trap (core dumped)  astroid
```

[thread.zip](https://github.com/astroidmail/astroid/files/3587609/thread.zip)

**Comment by serussell** [comment] 2019-09-09 20:10
Maybe not related; I'm getting these crashes on most operations now... like composition.  Maybe it's related to the process forking code?  This has started happening when I try to compose messages:

```
[15:08:19] [0x00007f026747dc00] [M] [info] re: using installed resource: /usr/local/share/astroid/ui/edit-message.glade
[15:08:19] [0x00007f026747dc00] [M] [info] em: msg id: 1568059699.p4ys28i53p.astroid@glamdring.none
[15:08:19] [0x00007f026747dc00] [M] [info] em: tmpfile: "/home/ser/.cache/astroid/1568059699.p4ys28i53p.astroid@glamdring.none"
[15:08:19] [0x00007f026747dc00] [M] [debug] theme: loading..
[15:08:19] [0x00007f026747dc00] [M] [warning] pc: DEBUG build. no local extension found. adding installed path.
[15:08:19] [0x00007f026747dc00] [M] [info] pc: adding /usr/local/lib/astroid/web-extensions to web extension search path.
[15:08:19] [0x00007f026747dc00] [M] [warning] pc: id: 2
[15:08:19] [0x00007f026747dc00] [M] [debug] pc: socket: 
[15:08:20] [0x00007faaa4f7a700] [E] [warning] reader thread: could not read message size
[15:08:20] [0x00007faaa4f7a700] [E] [debug] reader thread exit.
[1]    19739 segmentation fault (core dumped)  astroid
```

I'm going to reboot here in a moment; strangely, a lot of Astroid issues seem to be resolved by a reboot.

**Comment by serussell** [comment] 2019-09-09 23:53
I'm convinced now that it's any user-initiated action that forks off a process, such as GPG or gvim.  Is there a way I can verify this?  It doesn't happen with the background polling script, even if that's initiated by hotkey, but it does with viewing a message that has a PGP signature, or composing a message.  The log always says something similar:

```
[17:58:24] [0x00007f1355817c00] [M] [info] re: using installed resource: /usr/local/share/astroid/ui/edit-message.glade
[17:58:24] [0x00007f1355817c00] [M] [info] em: msg id: 1568069904.5jszltte31.astroid@glamdring.none
[17:58:24] [0x00007f1355817c00] [M] [info] em: tmpfile: "/home/ser/.cache/astroid/1568069904.5jszltte31.astroid@glamdring.none"
[17:58:24] [0x00007f1355817c00] [M] [debug] theme: loading..
[17:58:24] [0x00007f1355817c00] [M] [warning] pc: DEBUG build. no local extension found. adding installed path.
[17:58:24] [0x00007f1355817c00] [M] [info] pc: adding /usr/local/lib/astroid/web-extensions to web extension search path.
[17:58:24] [0x00007f1355817c00] [M] [warning] pc: id: 3
[17:58:24] [0x00007f1355817c00] [M] [debug] pc: socket: 
[1]    32026 segmentation fault (core dumped)  astroid
```

I rebooted, deleted the installed .../lib/astroid, .../share/astroid, and .../bin/astroid files/dirs, and did a clean checkout+build+install.  Finally, I ran astroid with strace and this was at the end:

```
getcwd("/home/ser", 128)                = 10
stat("/home/ser/libtvextension.so", 0x7ffca50b9670) = -1 ENOENT (No such file or directory)
write(2, "[18:52:06] [0x00007f9fe0417c00] "..., 111[18:52:06] [0x00007f9fe0417c00] [M] [warning] pc: DEBUG build. no local extension found. adding installed path.) = 111
write(2, "\n", 1
)                       = 1
write(2, "[18:52:06] [0x00007f9fe0417c00] "..., 121[18:52:06] [0x00007f9fe0417c00] [M] [info] pc: adding /usr/local/lib/astroid/web-extensions to web extension search path.) = 121
write(2, "\n", 1
)                       = 1
write(2, "[18:52:06] [0x00007f9fe0417c00] "..., 55[18:52:06] [0x00007f9fe0417c00] [M] [warning] pc: id: 2) = 55
write(2, "\n", 1
)                       = 1
write(2, "[18:52:06] [0x00007f9fe0417c00] "..., 56[18:52:06] [0x00007f9fe0417c00] [M] [debug] pc: socket: ) = 56
write(2, "\n", 1
)                       = 1
umask(077)                              = 022
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 45
fcntl(45, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(45, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
setsockopt(45, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
setsockopt(45, SOL_SOCKET, SO_REUSEPORT, [0], 4) = 0
bind(45, {sa_family=AF_UNIX, sun_path=@""}, 3) = -1 EADDRINUSE (Address already in use)
close(45)                               = 0
futex(0x7f9fe55ac060, FUTEX_WAKE_PRIVATE, 2147483647) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x46} ---
+++ killed by SIGSEGV (core dumped) +++
[1]    47342 segmentation fault (core dumped)  strace astroid
```

**Comment by gauteh** [comment] 2019-09-10 06:13
The first two crashes seem to be related. Maybe something related to the communication between the web process and the main. But could also be caused by abrupt term of one of them. Do you have a stack trace from gdb (bt) ? The pgp type spawning is managed by gmime, so that is code outside astroid. I think that the examples you have mentioned all spawn and read processes in different ways. Do you also get the errors if you try with test clean db with just a couple of messages. E.g. build/astroid -t in repo?

**Comment by serussell** [comment] 2019-09-13 15:42
Yes, reverting to 582cd35 fixes it for me.

**Comment by gauteh** [comment] 2019-10-22 08:18
Think this is fixed now.

**Closed by gauteh** 2019-10-22 08:18 UTC
