### ISSUE TITLE
Catching Dumb Mistakes Before Sending

### ISSUE THREAD

**Issue by Radvendii** [astroidmail/astroid#245] opened 2016-12-14 19:12 UTC
I sent out an email at about 7AM this morning, and I came back at 2PM and it hadn't sent. The reason being that I had forgotten to include a "to" address! Then when I re-sent the message, I forgot the attachments!

So I thought of a feature we could add to astroid that would solve both of these issues. If we could run a script over the message before it sends to check it for possible errors, and then have some confirmation that those are intentional things before sending. So for example checking that there is something in the "to" field, and checking that if there is the word "attachment" or "attached" somewhere in your email, you actually have something attached.

I suggest that there should be some default scripts already turned on (such as checking that there is something in the "to" field but with the option to turn any of these off, and way to add user-defined scripts.

I don't have time right now to look at implementing this, but if people think this is a good idea and nobody wants to do it right now, I can try to implement it later.

**Comment by gauteh** [comment] 2016-12-14 22:01
Hi, Yes. I think this would be a nice feature. The best might be to
set up a plugin for this so that you could use Python's gmime bindings
to read and check the e-mail.

The method then returns a passed/failed status and an error message with
can be used to describe what the problem is, then we could present that
to ask whether the user wants to send the e-mail still. What do you
think?

Defaults, like you suggested, could be tested and implemented anyway.

If you have the chance to work on a patch for this that would be great.

**Comment by mxmehl** [comment] 2016-12-23 14:55
+1. With Thunderbird I liked the attachment reminder. You're able to define specific words (e.g. attachment, attached, anhang, anbei) and if one of those words is in the mail, the clients asks you whether you really want to send the mail without any attachment (if there isn't any).

I agree that having this as a plugin would be the best solution to keep astroid slim. I would be happy to test your implementations!

**Comment by kirschner** [comment] 2016-12-23 15:48
* mxmehl <notifications@github.com> [2016-12-23 06:55:59 -0800]:

> +1. With Thunderbird I liked the attachment reminder. You're able to
> define specific words (e.g. attachment, attached, anhang, anbei) and
> if one of those words is in the mail, the clients asks you whether you
> really want to send the mail without any attachment (if there isn't
> any).

That would be really good. 

Maybe it helsp; in mutt you can use a vim plugin for that:
http://www.vim.org/scripts/script.php?script_id=1015

**Comment by gauteh** [comment] 2016-12-24 12:04
Matthias Kirschner writes on desember 23, 2016 16:48:
> * mxmehl <notifications@github.com> [2016-12-23 06:55:59 -0800]:
> 
>> +1. With Thunderbird I liked the attachment reminder. You're able to
>> define specific words (e.g. attachment, attached, anhang, anbei) and
>> if one of those words is in the mail, the clients asks you whether you
>> really want to send the mail without any attachment (if there isn't
>> any).
> 
> That would be really good. 
> 

Please test #252, added config option: "editor.attachment_words".

Also checks for missing to, cc, or bcc fields.

**Comment by gauteh** [comment] 2016-12-25 08:59
Fixed in #252.

**Closed by gauteh** 2016-12-25 08:59 UTC

**Comment by hugoroy** [comment] 2017-02-25 20:13
Thanks, that's very useful!

does somebody want to make a note for it in the wiki? Right now the default config assumes it's English with 'attach' but people writing in other languages may be interested in editing this feature.

@Radvendii @mxmehl @kirschner do you want to edit the wiki? :-)

**Comment by mxmehl** [comment] 2017-02-28 16:38
Thanks for the reminder, I'll write something :)

**Comment by mxmehl** [comment] 2017-02-28 17:19
Added https://github.com/astroidmail/astroid/wiki/Missing-Attachment-Reminder to the wiki

**Comment by gauteh** [comment] 2017-03-02 08:09
Max writes on februar 28, 2017 18:19:
> Added https://github.com/astroidmail/astroid/wiki/Missing-Attachment-Reminder to the wiki
> 

Thanks :)
