### ISSUE TITLE
Core Dumped with no apparent cause

### ISSUE THREAD

**Issue by cinghiopinghio** [astroidmail/astroid#423] opened 2017-10-23 14:51 UTC
As per the title, since last update I have a core dumped error without apparent cause.
In the following you can find the trace of the debug log.

Any Idea?

```
[16:36:18.210044] [0x00007f1f4f26f080] [info] welcome to astroid! - 0.10.2
[16:36:18.210097] [0x00007f1f4f26f080] [debug] utf8: true, UTF-8
[16:36:18.211735] [0x00007f1f4f26f080] [debug] HOME: /home/mauro
[16:36:18.211767] [0x00007f1f4f26f080] [info] cf: loading: "/home/XXX/.config/astroid/config"
[16:36:18.212096] [0x00007f1f4f26f080] [info] cf: version: 9
[16:36:18.212381] [0x00007f1f4f26f080] [info] notmuch db: /home/XXX/.mail
[16:36:18.212391] [0x00007f1f4f26f080] [info] date: init.
[16:36:18.212445] [0x00007f1f4f26f080] [info] db path: /home/XXX/.mail
[16:36:18.212529] [0x00007f1f4f26f080] [info] keybindings: loading user bindings from: /home/XXX/.config/astroid/keybindings
[16:36:18.212545] [0x00007f1f4f26f080] [debug] ky: parsing line: main_window.search=/ 
[16:36:18.212558] [0x00007f1f4f26f080] [debug] ky: parsing line: main_window.search_tag=C-/ 
[16:36:18.212582] [0x00007f1f4f26f080] [debug] ky: parsing run-hook: thread_index.run(hooks::toggleTag killed %1)=X
[16:36:18.212590] [0x00007f1f4f26f080] [debug] ky: run: thread_index.run(X): hooks::toggleTag killed %1
[16:36:18.212597] [0x00007f1f4f26f080] [debug] ky: parsing run-hook: thread_view.run(hooks::toggleMailTag killed %2)=X
[16:36:18.212604] [0x00007f1f4f26f080] [debug] ky: run: thread_view.run(X): hooks::toggleMailTag killed %2
[16:36:18.212610] [0x00007f1f4f26f080] [debug] ky: parsing line: thread_index.archive_thread=A 
[16:36:18.212619] [0x00007f1f4f26f080] [debug] ky: parsing line: thread_index.multi.archive=A 
[16:36:18.212626] [0x00007f1f4f26f080] [debug] ky: parsing line: thread_index.archive=A 
[16:36:18.212637] [0x00007f1f4f26f080] [info] searches: loading saved searches..
[16:36:18.212980] [0x00007f1f4f26f080] [debug] searches: loading history..
[16:36:18.213129] [0x00007f1f4f26f080] [info] ac: initializing accounts..
[16:36:18.213174] [0x00007f1f4f26f080] [info] ac: setup account: gmail for Xxx Yyy (default: true)
[16:36:18.213191] [0x00007f1f4f26f080] [info] ac: setup account: ucl for Xxx Yyy (default: false)
[16:36:18.213219] [0x00007f1f4f26f080] [info] ac: setup account: linux for Xxx (default: false)
[16:36:18.213240] [0x00007f1f4f26f080] [info] plugins: starting manager..
[16:36:18.213304] [0x00007f1f4f26f080] [debug] plugins: adding path: /usr/share/astroid/plugins
[16:36:18.213335] [0x00007f1f4f26f080] [debug] plugin: adding path: /home/XXX/.config/astroid/plugins
[16:36:18.213425] [0x00007f1f4f26f080] [debug] plugins: refreshing..
[16:36:18.213491] [0x00007f1f4f26f080] [debug] plugins: found 1 plugins.
[16:36:18.213498] [0x00007f1f4f26f080] [debug] plugins: loading: icons plugin
gicons: plugin loaded
[16:36:18.308635] [0x00007f1f4f26f080] [debug] plugins: loaded: icons plugin
[16:36:18.308828] [0x00007f1f4f26f080] [debug] plugins: registering threadview plugin..
[16:36:18.308879] [0x00007f1f4f26f080] [info] global actions: set up.
[16:36:18.308925] [0x00007f1f4f26f080] [info] poll: setting up.
[16:36:18.308950] [0x00007f1f4f26f080] [debug] poll: interval: 60
[16:36:18.308958] [0x00007f1f4f26f080] [debug] poll: requested..
[16:36:18.308965] [0x00007f1f4f26f080] [info] db: open db read-only, waiting for lock..
[16:36:18.308969] [0x00007f1f4f26f080] [debug] db: read-only got lock.
[16:36:18.309182] [0x00007f1f4f26f080] [debug] db: open time: 0.217 ms.
[16:36:18.309196] [0x00007f1f4f26f080] [info] db: closing db.
[16:36:18.309242] [0x00007f1f4f26f080] [debug] db: ro: waiting for lock to close..
[16:36:18.309247] [0x00007f1f4f26f080] [debug] db: ro: closing..
[16:36:18.309251] [0x00007f1f4f26f080] [debug] poll: revision before poll: 157683
[16:36:18.309259] [0x00007f1f4f26f080] [info] poll: polling: /home/XXX/.config/astroid/poll.sh
[16:36:18.311056] [0x00007f1f4f26f080] [warning] astroid: starting a new window..
[16:36:18.320948] [0x00007f1f4f26f080] [info] db: open db read-only, waiting for lock..
[16:36:18.320975] [0x00007f1f4f26f080] [debug] db: read-only got lock.
[16:36:18.321119] [0x00007f1f4f26f080] [debug] db: open time: 0.177 ms.
[16:36:18.321311] [0x00007f1f4f26f080] [info] db: loaded 198 tags.
[16:36:18.321318] [0x00007f1f4f26f080] [info] db: closing db.
[16:36:18.321336] [0x00007f1f4f26f080] [debug] db: ro: waiting for lock to close..
[16:36:18.321341] [0x00007f1f4f26f080] [debug] db: ro: closing..
[16:36:18.325477] [0x00007f1f4f26f080] [debug] mw: init, id: 1
[16:36:18.325516] [0x00007f1f4f26f080] [info] re: using installed resource: /usr/share/astroid/ui/icons/icon_color.png
[16:36:18.332751] [0x00007f1f4f26f080] [info] astroid: got query: inbox: tag:inbox and not tag:killed
[16:36:18.334583] [0x00007f1f4f26f080] [info] re: using installed resource: /usr/share/astroid/ui/no-mail.png
[16:36:18.335921] [0x00007f1f4f26f080] [info] ky: run, binding: thread_index.run(X) (userdefined: true) to: hooks::toggleTag killed %1
[16:36:18.336834] [0x00007f1f4f26f080] [debug] pm: add pane
[16:36:18.337038] [0x00007f1f2a469700] [info] db: open db read-only, waiting for lock..
[16:36:18.337075] [0x00007f1f2a469700] [debug] db: read-only got lock.
[16:36:18.337440] [0x00007f1f2a469700] [debug] db: open time: 0.765 ms.
[16:36:18.337504] [0x00007f1f2a469700] [debug] ql: refresh stats..
[16:36:18.338353] [0x00007f1f4f26f080] [debug] mw: does not have focus, will not grab modal.
[16:36:18.338497] [0x00007f1f4f26f080] [debug] mw: set active: 0, current: 0
[16:36:18.338511] [0x00007f1f4f26f080] [debug] mw: does not have focus, will not grab modal.
[16:36:18.338521] [0x00007f1f4f26f080] [debug] mw: set active: 0, current: 0
[16:36:18.338526] [0x00007f1f4f26f080] [debug] mw: does not have focus, will not grab modal.
zsh: segmentation fault (core dumped)  astroid --log-level trace
```

**Comment by gauteh** [comment] 2017-10-23 15:20
Can you send the backtrace from the core?

**Comment by cinghiopinghio** [comment] 2017-10-23 15:25
sorry for my ignorance, how can I do that?

**Comment by cinghiopinghio** [comment] 2017-10-23 15:42
As a comment I built `astroid` ignoring the errors on the tests I reported on #414

**Comment by gauteh** [comment] 2017-10-23 15:50
Cinghio Pinghio writes on oktober 23, 2017 17:25:
> sorry for my ignorance, how can I do that?

It is a distribution dependent, but reading this: https://ask.fedoraproject.org/en/question/98776/where-is-core-dump-located/ it seems that you can use:

$ coredumpctl gdb astroid
$ (gdb) bt

but the core file size might be set to zero by default? In that case you 
have to use ulimit -c unlimited (or something) and see if you can 
reproduce the crash. From the log it is hard to see what could have 
happened. Were you doing something when it crashed?

**Comment by cinghiopinghio** [comment] 2017-10-24 08:49
Voilá the coredump, I don't see any evident problem:
[pastebin](https://bin.disroot.org/?97c967d33dfa516e#7FjMr9TUbcUW/Jc0uO6MRB05NkMWlYPCaDseq7Wlw9U=)

**Comment by gauteh** [comment] 2017-10-24 08:50
This looks like a duplicate of this one: https://github.com/astroidmail/astroid/issues/405 - use the same gmime version for both notmuch and astroid.

**Comment by cinghiopinghio** [comment] 2017-10-24 09:24
This seems to require `notmuch` to be compiled by myself!!!
I don't have time right now to stop my email workflow... maybe I'll get back to this later on.

**Comment by gauteh** [comment] 2017-10-24 09:28
Cinghio Pinghio writes on oktober 24, 2017 11:24:
> This seems to require `notmuch` to be compiled by myself!!!
> I don't have time right now to stop my email workflow... maybe I'll get back to this later on.

You could also use gmime2 with astroid (easiest to uninstall gmime3 if 
possible). Hopefully this will resolve it. Closing as duplicate.

**Closed by gauteh** 2017-10-24 09:28 UTC
Labels: need-info

**Comment by cinghiopinghio** [comment] 2017-10-24 13:29
Ok, uninstalling `gmime3` was pretty straight forward. I confirm that this was the cause.
Maybe it is possible at compile time to check which version is used by `notmuch` and use the same??
Not sure if this is even possible...

**Comment by gauteh** [comment] 2017-10-24 13:34
Cinghio Pinghio writes on oktober 24, 2017 15:29:
> Ok, uninstalling `gmime3` was pretty straight forward. I confirm that this was the cause.
> Maybe it is possible at compile time to check which version is used by `notmuch` and use the same??
> Not sure if this is even possible...

Not sure, not too hard to specify a config option for astroid build 
system to use one or the other - but I doubt it will make a difference 
in the incoming bug-reports.
