### ISSUE TITLE
date is not always shown

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#213] opened 2016-09-07 10:11 UTC
i have mails where the date is not shown. i assume the "Date:" headerfield is used. i checked all mails and found they have proper date fields. gauteh suggested parsing the format fails. these fail:

Date: Tue, 19 Aug 2014 16:11:44 +0200
Date: Mon, 9 May 2016 13:26:57 +0000

but this one succeeds:

Date: Thu, 1 Sep 2016 14:32:16 +0000

all dates look fine for me. even when replying to such an email the date is missing in the prefix. does someone else see that problem too? any idea?

**Comment by gauteh** [comment] 2016-09-07 11:09
M. Dietrich writes on september 7, 2016 12:11:
> i have mails where the date is not shown. i assume the "Date:" headerfield is used. i checked all mails and found they have proper date fields. gauteh suggested parsing the format fails. these fail:
> 
> Date: Tue, 19 Aug 2014 16:11:44 +0200
> Date: Mon, 9 May 2016 13:26:57 +0000
> 
> but this one succeeds:
> 
> Date: Thu, 1 Sep 2016 14:32:16 +0000
> 
> all dates look fine for me. even when replying to such an email the date is missing in the prefix. does someone else see that problem too? any idea?

I am not able to reproduce with test emails with those date headers. Do
you have a test-email that you could send?

Have a look at #214, it includes a few test e-mails with those dates.
They all parse fine, and they show up in the thread-view just fine.

I assume this is missing in thread-view?

**Comment by emdete** [comment] 2016-09-07 11:23
this is strange: in the source i see

LOG (debug) << "tv: focusing: " << m->date ();

but the log is on warning level:

[12:16:30.767311] [0x00007ff2964e4ac0] [warning] tv: focusing: Mon, 09 May 2016 13:26:57 +0000

**Comment by gauteh** [comment] 2016-09-07 11:25
Weird, maybe try a complete clean: $ scons -c, maybe something changed with the logging library.

**Comment by emdete** [comment] 2016-09-07 11:25
i doubt it depends on the date header. i would like to enhance logging. as you see from the previous post, the logging (m->date ();) succeeds for those cases as well (btw: why is the date logged for the focusing?).

**Comment by gauteh** [comment] 2016-09-07 12:26
Fixed in #213.

**Closed by gauteh** 2016-09-07 12:26 UTC
