### ISSUE TITLE
tests: memory access violation

### ISSUE THREAD

**Issue by serussell** [astroidmail/astroid#414] opened 2017-10-09 17:41 UTC
I upgraded some software and had to recompile Astroid because Boost changed.  I'm getting a couple of memory access violation errors in the build process, and am not sure how to proceed:

```
db: running test query..
query: *, approx: 10 threads.
unknown location(0): fatal error: in "Notmuch/notmuch_threads_move_to_next_fail": memo
ry access violation at address: 0x00000018: no mapping at fault address
../tests/test_notmuch.cc(95): last checkpoint
--- stderr ---

*** 1 failure is detected in the test module "TestNotmuch"
```

and

```
*** 1 failure is detected in the test module "TestCrypto"
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::log::v2_mt_posix::system_error> >'
  what():  Failed to set TLS value: Invalid argument
```

There's another notmuch failure, but for the life of me I can't determine what menon thinks failed:

```
*** No errors detected
-------

11/15 notmuch                                 FAIL     0.12 s
```

... all of the other tests before that report OK.  I remember encountering the memory access issues before when trying to compile Astroid from git, months ago; I eventually gave up trying and was thrilled when building from AUR worked.  However, now the problem is plaguing AUR and I'm sad again.

Is anybody else seeing this?  I re-installed `notmuch` and all things `openssl
` before my last Astroid attempt.

[testlog.txt](https://github.com/astroidmail/astroid/files/1369396/testlog.txt)

**Comment by gauteh** [comment] 2017-10-09 18:48
Does it work to just build astroid: ninja astroid
?

Should be able to run it in that case hopefully.


man. 9. okt. 2017 kl. 19:41 skrev Sean Russell <notifications@github.com>:

**Comment by gauteh** [comment] 2017-10-09 21:19
The TLS error is a red herring, its a secondary error from the error further up the log. You could maybe try to run `gpgconf --kill all` before running the tests.

**Comment by gauteh** [comment] 2017-10-09 21:23
(you can also try latest master, this should probably also fix the AUR build)

**Comment by gauteh** [comment] 2017-10-09 21:31
The `move_to_next_fail` is a bug in notmuch/xapian that is randomly re-produced. If possible the test should be marked as possible fail.

**Comment by gauteh** [comment] 2017-10-11 10:01
Any new info? Going to close otherwise.

**Comment by serussell** [comment] 2017-10-11 16:05
I haven't had a chance to look at it again, and probably won't until tomorrow at the earliest.

**Comment by cinghiopinghio** [comment] 2017-10-13 07:55
Hi, I'm experiencing the same problem to update to the latest 0.10.2 version on archlinux.
`ninjia` fails test 11, 12 and 15.

During the `meson` initializations all checks are `OK` except:
```
Checking for function "notmuch_database_index_file": NO
Has header "sass_context.h": NO
```

here the logs:

```
11/15 notmuch                                 FAIL     0.10 s

--- command ---
NOTMUCH_CONFIG='/home/USER/.cache/pacaur/astroid/src/astroid-0.10.2/build/tests/mail/test_config' GNUPGHOME='/home/USER/.cache/pacaur/astroid/src/astroid-0.10.2/build/tests/test_home/gnupg' /home/USER/.cache/pacaur/astroid/src/astroid-0.10.2/build/test_notmuch
--- stdout ---
Running 2 test cases...
db: running test query..
query: *, approx: 11 messages.
thread:0000000000000009, message: Re: [astroidmail/astroid] Email as attachment (#237)
thread:0000000000000006, message: 󾔰󾓶󾓶 RE: Your Bonus Edwards Benj  󾔰󾓶󾓶
thread:0000000000000001, message: debian-user-digest Digest V2016 #172
thread:000000000000000a, message: quote test
thread:0000000000000007, message: [Fwd] Re: [astroid] Keybinding configuration (#21)
thread:0000000000000002, message: asdfsadf
thread:0000000000000003, message: 
thread:0000000000000005, message: Date test 2
thread:0000000000000008, message: Re: [sup-talk] Indexing messages without ruby
thread:0000000000000004, message: Date test 1
thread:0000000000000008, message: [sup-talk] Indexing messages without ruby
db: running test query..
query: *, approx: 10 threads.
unknown location(0): fatal error: in "Notmuch/notmuch_threads_move_to_next_fail": memory access violation at address: 0x00000018: no mapping at fault address
../tests/test_notmuch.cc(95): last checkpoint
--- stderr ---

*** 1 failure is detected in the test module "TestNotmuch"
-------

12/15 notmuch (standalone)                    FAIL     0.34 s

--- command ---
NOTMUCH_CONFIG='/home/USER/.cache/pacaur/astroid/src/astroid-0.10.2/build/tests/mail/test_config' GNUPGHOME='/home/USER/.cache/pacaur/astroid/src/astroid-0.10.2/build/tests/test_home/gnupg' /home/USER/.cache/pacaur/astroid/src/astroid-0.10.2/build/test_notmuch_standalone
--- stdout ---
db: running test query..
query: *, approx: 10 threads.
-------

15/15 crypto                                  FAIL     0.80 s

--- command ---
NOTMUCH_CONFIG='/home/USER/.cache/pacaur/astroid/src/astroid-0.10.2/build/tests/mail/test_config' GNUPGHOME='/home/USER/.cache/pacaur/astroid/src/astroid-0.10.2/build/tests/test_home/gnupg' /home/USER/.cache/pacaur/astroid/src/astroid-0.10.2/build/test_crypto
--- stdout ---
Processed 1 file in almost no time.
Added 1 new message to the database.
thread:000000000000000c  0 mins. ago [1/1] Charlie Root; test gpg e-mail (encrypted inbox unread)
thread:0000000000000009   2016-12-07 [1/1] Hugo Roy; [astroidmail/astroid] Email as attachment (#237) (inbox unread)
thread:0000000000000006   2016-08-02 [1/1] 󾔰 C0ngratuLations 󾔰; 󾔰󾓶󾓶 RE: Your Bonus Edwards Benj  󾔰󾓶󾓶 (inbox unread)
thread:0000000000000001   2016-02-22 [1/1] debian-user-digest-request@lists.debian.org; debian-user-digest Digest V2016 #172 (inbox signed unread)
thread:000000000000000a   2016-02-22 [1/1] Charlie Root; quote test (inbox unread)
thread:0000000000000007   2016-01-03 [1/1] Hugo Roy; [Fwd] Re: [astroid] Keybinding configuration (#21) (inbox signed unread)
thread:0000000000000002   2015-04-12 [1/1] BASDF; asdfsadf (inbox unread)
thread:0000000000000003   2014-10-27 [1/1] tst@asfdasas.sdf;  (inbox unread)
thread:0000000000000005   2014-08-19 [1/1] Dater; Date test 2 (inbox unread)
thread:0000000000000008   2009-10-20 [2/2] Carl Worth; [sup-talk] Indexing messages without ruby (inbox signed unread)
thread:0000000000000004   2009-10-15 [1/1] Dater; Date test 1 (inbox unread)
Running 7 test cases...
unknown location(0): fatal error: in "GPGEncryption/crypto_too_many_open_files": memory access violation at address: 0x00000018: no mapping at fault address
../tests/test_crypto.cc(222): last checkpoint
```

I tried to run `gpgconf --kill all` before compiling as suggested without success

**Comment by gauteh** [comment] 2017-10-13 08:47
Hi,

what distribution do you have and what version of notmuch and xapian are 
you running?

Regards, Gaute

**Comment by gauteh** [comment] 2017-10-13 09:01
Note that this is the tests, you can turn off the tests and keep 
compiling.

**Comment by cinghiopinghio** [comment] 2017-10-13 11:43
I'm running `notmuch` 0.25 and `xapian` 1.4.4 on archlinux.
I know that I can disable tests, but I wanted to report this problem to you.

thanks. great app.

**Comment by gauteh** [comment] 2017-10-13 11:47
Cinghio Pinghio writes on oktober 13, 2017 13:43:
> I'm running `notmuch` 0.25 and `xapian` 1.4.4 on archlinux.
> I know that I can disable tests, but I wanted to report this problem to you.
> 
> thanks. great app.

Ok, thanks. The notmuch/xapian errors are random and seem to be caused 
by some sort of race conditions. I've never been able to reliably make 
them fail.

The crypto error is trickier-- could you pastebin meson-logs/testlog.txt somewhere?

Regards, Gaute

**Comment by cinghiopinghio** [comment] 2017-10-13 11:59
Voilá:
- [meson-log.txt](https://pastebin.com/KEPtYKGy)
- [testlog.txt](https://pastebin.com/ZKMnCDvn)

**Comment by gauteh** [comment] 2017-10-13 12:08
Cinghio Pinghio writes on oktober 13, 2017 13:59:
> Voilá:
> - [meson-log.txt](https://pastebin.com/KEPtYKGy)
> - [testlog.txt](https://pastebin.com/ZKMnCDvn)

I disabled parallel tests (on 'master'), I think the crypto failure 
happened because the other notmuch test was failing. Could you try to 
build astroid-git?

Regards, Gaute

**Comment by cinghiopinghio** [comment] 2017-10-13 12:23
Unfortunately it still fails even with `astroid-git`

**Comment by gauteh** [comment] 2017-10-13 12:24
Cinghio Pinghio writes on oktober 13, 2017 14:23:
> Unfortunately it still fails even with `astroid-git`

The crypto-test as well? Could you re-post the test-logs.

Cheers

**Comment by cinghiopinghio** [comment] 2017-10-13 12:39
Yeah, the same three failures!
[testlog.txt](https://pastebin.com/hwG8RyMG)

**Comment by gauteh** [comment] 2017-11-03 10:47
Could you try to cd to the build dir and do `./test_notmuch_standalone`?  If it fails, pleas also do so with gdb to get a stacktrace and maybe with valgrind.

**Comment by gauteh** [comment] 2017-11-03 12:01
So this error turned out to be related to the different gmime versions, can anyone still confirm that this error happens as long as you are using the same GMime version for both astroid and notmuch?

**Comment by serussell** [comment] 2017-11-03 12:30
I'll try a recompile this weekend and report back.

**Comment by gauteh** [comment] 2017-11-03 12:38
Not able to add a warning to meson because of: https://github.com/mesonbuild/meson/issues/2576

**Comment by cinghiopinghio** [comment] 2017-11-03 14:10
For my part, compiling `astroid` with the same `gmime` version as `notmuch` solved the problem and the errors (automagically) disappeared.

**Comment by gauteh** [comment] 2017-11-04 08:03
Thanks, I've added a test to the meson script to detect if conflicting gmime versions have been used.

**Closed by gauteh** 2017-11-04 08:03 UTC
Labels: bug, notmuch

**Comment by serussell** [comment] 2017-11-04 15:41
Curiously, I just updated from git and rebuilt astroid, and it's linked two both gmime-2 and gmime-3:

```
➜  build git:(master) ✗ ldd ./astroid | grep gmime
        libgmime-3.0.so.0 => /usr/lib/libgmime-3.0.so.0 (0x00007f2834dd5000)
        libgmime-2.6.so.0 => /usr/lib/libgmime-2.6.so.0 (0x00007f2821f88000)
➜  build git:(master) ✗ ldd `which notmuch` | grep gmime
        libgmime-2.6.so.0 => /usr/lib/libgmime-2.6.so.0 (0x00007f70c11af000)
```

This still segfaults, but I'm about to clean everything and try one more time.  I do see that the load address for the two versions of libgmime is different, but I don't know if that's significant.

**Comment by gauteh** [comment] 2017-11-04 15:44
Sean Russell writes on november 4, 2017 16:41:
> Curiously, I just updated from git and rebuilt astroid, and it's linked two both gmime-2 and gmime-3:
> 
> ```
> ➜  build git:(master) ✗ ldd ./astroid | grep gmime
>         libgmime-3.0.so.0 => /usr/lib/libgmime-3.0.so.0 (0x00007f2834dd5000)
>         libgmime-2.6.so.0 => /usr/lib/libgmime-2.6.so.0 (0x00007f2821f88000)
> ➜  build git:(master) ✗ ldd `which notmuch` | grep gmime
>         libgmime-2.6.so.0 => /usr/lib/libgmime-2.6.so.0 (0x00007f70c11af000)
> ```
> 
> This still segfaults, but I'm about to clean everything and try one more time.  I do see that the load address for the two versions of libgmime is different, but I don't know if that's significant. 
> 

Yes, so this is caused by having notmuch linked against gmime 2 while 
astroid is compiled and linked against gmime 3. The gmime 2 dep is 
probably pulled in through notmuch. Either downgrade to gmime 2 while 
compiling astroid, or re-compile notmuch against gmime 3.

**Comment by serussell** [comment] 2017-11-04 19:52
notmuch is coming from Arch on my machine, so I'll try removing gmime3

**Comment by serussell** [comment] 2017-11-05 19:56
I uninstalled everything notmuch that was provided by Arch, uninstalled gmime-2, downloaded the notmuch source archive and compiled it.  Now

```
➜  astroid git:(master) ✗ ldd `which notmuch` | grep gmime
        libgmime-3.0.so.0 => /usr/lib/libgmime-3.0.so.0 (0x00007f4b54a8b000)
```

which looks good, right?  However, when I try compiling astroid, I now get:

```
Native dependency gmime-3.0 found: YES 3.0.3
Dependency gmime-2.6 found: NO
...
Library notmuch found: YES
Checking for function "notmuch_database_index_file": NO

Meson encountered an error in file meson.build, line 46, column 2:
Error encountered: gmime version matches between astroid and notmuch: NO. You must compile and link both astroid and notmuch against the same gmime version.
```

Looking at the logs, it looks like the real error is a missing notmuch library:

```
Program stderr:

/tmp/tmpa0_qh8w2/output.exe: error while loading shared libraries: libnotmuch.so.5: cannot open shared object file: No such file or directory
```

Is the error message a red herring?  Why did `meson build` say it found the notmuch library, but the error log says it didn't?  I have no other version of gmime than 3.0 install -- why is meson saying that the versions are different?

Thanks.

**Comment by gauteh** [comment] 2017-11-05 21:09
Sean Russell writes on november 5, 2017 20:56:
> I uninstalled everything notmuch that was provided by Arch, uninstalled gmime-2, downloaded the notmuch source archive and compiled it.  Now
> 
> ```
> ➜  astroid git:(master) ✗ ldd `which notmuch` | grep gmime
>         libgmime-3.0.so.0 => /usr/lib/libgmime-3.0.so.0 (0x00007f4b54a8b000)
> ```
> 
> which looks good, right?  However, when I try compiling astroid, I now get:
> 
> ```
> Native dependency gmime-3.0 found: YES 3.0.3
> Dependency gmime-2.6 found: NO
> ...
> Library notmuch found: YES
> Checking for function "notmuch_database_index_file": NO
> 
> Meson encountered an error in file meson.build, line 46, column 2:
> Error encountered: gmime version matches between astroid and notmuch: NO. You must compile and link both astroid and notmuch against the same gmime version.
> ```
> 
> Looking at the logs, it looks like the real error is a missing notmuch library:
> 
> ```
> Program stderr:
> 
> /tmp/tmpa0_qh8w2/output.exe: error while loading shared libraries: libnotmuch.so.5: cannot open shared object file: No such file or directory
> ```
> 
> Is the error message a red herring?  Why did `meson build` say it found the notmuch library, but the error log says it didn't?  I have no other version of gmime than 3.0 install -- why is meson saying that the versions are different?
> 

There could be something wrong with the meson cache. Could you try 
to re-generate the build dir from scratch?

**Comment by serussell** [comment] 2017-11-06 12:15
I removed gmime3, installed gmime-2 & notmuch from Arch, recompiled Astroid (against gmime-2) and it worked.  It only seems to have trouble with gmime3.

So, to summarize for any other seekers: Astroid works on Arch only if gmime3 is _not_ installed, at all:

- Only gmime3 does not work
- gmime3 & gmime-2 does not work
- gmime-2 only **does** work.

**Comment by gauteh** [comment] 2017-11-06 12:53
Great! 

The essential part is that notmuch *and* astroid must use the *same* version of GMime, so either:

* GMime 3 (with or without GMime 2 installed, since both astroid and notmuch will prefer gmime 3)
* Compile notmuch from [AUR](https://aur.archlinux.org/packages/notmuch-runtime-git/)

or 

* Un-install GMime 3
* Use binary notmuch

The latter will change once GMime3 ships with Arch and notmuch by default is compiled against GMime 3, in which case there should be no need to fiddle around with GMime versions.

**Comment by mxmehl** [comment] 2017-11-06 13:20
@serussell Could you please add your findings in the astroid wiki? This seems to be a necessary information for many of astroid's users. Thanks!

**Comment by serussell** [comment] 2017-11-06 22:43
Hi,

I did download the notmuch source and compiled it with gmime3; this 
resulted in my previous report that Astroid claimed that it needed the same 
library as notmuch. At that point, only gmime3 was installed on my system, 
and notmuch was compiled against it. So, as far as I can tell, gmime3 does 
not work. I suspect it is related to the new gmime version check that was 
added, but this is only a guess based on the error message.

**Comment by gauteh** [comment] 2017-11-06 23:15
Sean Russell writes on november 6, 2017 23:43:
> Hi,
> 
> I did download the notmuch source and compiled it with gmime3; this 
> resulted in my previous report that Astroid claimed that it needed the same 
> library as notmuch. At that point, only gmime3 was installed on my system, 
> and notmuch was compiled against it. So, as far as I can tell, gmime3 does 
> not work. I suspect it is related to the new gmime version check that was 
> added, but this is only a guess based on the error message.
> 

Hm, ok. This could be caused by the build-cache. You might have to 
delete the build dir in-between to make meson check again for 
dependencies (probably didn't detect gmime-3).

The version-check does the same thing as the astroid code, so if it 
fails, you would encounter this bug either at test-time or run-time.
