### ISSUE TITLE
collect2: error: ld returned 1 exit status; ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by seniorivn** [astroidmail/astroid#421] opened 2017-10-13 14:02 UTC
```shell
meson build  
The Meson build system
Version: 0.42.1
Source dir: /home/ivn/projects/astroid
Build dir: /home/ivn/projects/astroid/build
Build type: native build
Project name: astroid
Native C compiler: ccache cc (gcc 7.2.0)
Native C++ compiler: ccache c++ (gcc 7.2.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/sbin/pkg-config (0.29.2)
Dependency gmime-3.0 found: NO
Native dependency gmime-2.6 found: YES 2.6.23
Dependency Boost (thread, filesystem, log_setup, log, date_time, system) found: YES 1.65.1
Library boost_program_options found: YES
Native dependency gtk+-3.0 found: YES 3.22.21
Native dependency gtkmm-3.0 found: YES 3.22.1
Native dependency webkitgtk-3.0 found: YES 2.4.11
Dependency threads found: YES
Library notmuch found: YES
Checking for function "notmuch_database_index_file": NO
Native dependency vte-2.91 found: YES 0.48.3
Native dependency libsass found: YES na
Has header "sass_context.h": NO
Has header "sass/context.h": YES
Configuring build_config.hh using configuration
Message: Building astroid: v0.10.2-2-g8c2a35d1
Native dependency libpeas-1.0 found: YES 1.20.0
Program g-ir-scanner found: YES (/usr/sbin/g-ir-scanner)
Program g-ir-compiler found: YES (/usr/sbin/g-ir-compiler)
Native dependency gobject-introspection-1.0 found: YES 1.52.1
Program tests/test_setup.sh found: YES (/home/ivn/projects/astroid/tests/test_setup.sh)
Dependency Boost (unit_test_framework) found: YES 1.65.1
Build targets in project: 20
 ivn@jarvis  ~/projects/astroid   master  cd build   
 ivn@jarvis  ~/projects/astroid/build   master  ls
build_config.hh  build.ninja  compile_commands.json  meson-logs  meson-private
 ivn@jarvis  ~/projects/astroid/build   master  ninja 
[63/95] Linking target gir_main.
FAILED: gir_main 
ccache c++  -o gir_main 'gir_main@exe/src_plugin_astroid_activatable.c.o' 'gir_main@exe/src_plugin_thread_view_activatable.c.o' 'gir_main@exe/src_plugin_thread_index_activatable.c.o' 'gir_main@exe/src_plugin_gir_main.c.o' -Wl,--no-undefined -Wl,--as-needed -pthread -Wl,--start-group -lgmime-2.6 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -Wl,--end-group -lboost_thread -lboost_filesystem -lboost_log_setup -lboost_log -lboost_date_time -lboost_system -lboost_program_options -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lgtkmm-3.0 -latkmm-1.6 -lgdkmm-3.0 -lgiomm-2.4 -lpangomm-1.4 -lglibmm-2.4 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lgio-2.0 -lcairomm-1.0 -lcairo -lsigc-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lwebkitgtk-3.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -ljavascriptcoregtk-3.0 -lglib-2.0 -lnotmuch -lvte-2.91 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lz -lpcre2-8 -lgnutls -lsass -lpeas-1.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgirepository-1.0 -lgobject-2.0 -lglib-2.0  
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_surface_get_width'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_surface_get_height'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_device_set_thread_aware'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_egl_device_create'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_surface_create_for_texture'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_glx_device_create'
collect2: error: ld returned 1 exit status
[64/95] Generating test_setup with a custom command.
setting up test suite:
======================
* stopping all gpg components..
source root ....: ../tests
build root .....: /home/ivn/projects/astroid/build/tests
* setting up notmuch test db..
* writing notmuch config: /home/ivn/projects/astroid/build/tests/mail/test_config
* install e-mail test corpus..
Found 16 total files (that's not much mail).
Processed 16 total files in almost no time.
Added 11 new messages to the database.
* set up test scripts..
* set up test home..
* set up theme..
----------------------
* setting up GPG..
~/projects/astroid/build/tests/test_home/gnupg ~/projects/astroid/build
gpg: keybox '/home/ivn/projects/astroid/build/tests/test_home/gnupg/pubring.kbx' created
gpg: Generating a basic OpenPGP key
gpg: done
gpg: Generating a basic OpenPGP key
gpg: done
gpg: key 4E5216FF66891E9D: public key "Tester1 (First tester) <gaute@astroidmail.bar>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: key 1C6186F8E511E755: public key "Tester2 (Second tester) <astrid@astroidmail.bar>" imported
gpg: Total number processed: 1
gpg:               imported: 1
~/projects/astroid/build
======================
[66/95] Linking target astroid.
FAILED: astroid 
ccache c++  -o astroid 'astroid@exe/src_modes_log_view.cc.o' 'astroid@exe/src_modes_mode.cc.o' 'astroid@exe/src_modes_thread_view_thread_view.cc.o' 'astroid@exe/src_modes_thread_view_web_inspector.cc.o' 'astroid@exe/src_modes_thread_view_dom_utils.cc.o' 'astroid@exe/src_modes_thread_view_theme.cc.o' 'astroid@exe/src_modes_paned_mode.cc.o' 'astroid@exe/src_modes_thread_index_thread_index_list_cell_renderer.cc.o' 'astroid@exe/src_modes_thread_index_query_loader.cc.o' 'astroid@exe/src_modes_thread_index_thread_index.cc.o' 'astroid@exe/src_modes_thread_index_thread_index_list_view.cc.o' 'astroid@exe/src_modes_saved_searches.cc.o' 'astroid@exe/src_modes_edit_message.cc.o' 'astroid@exe/src_modes_reply_message.cc.o' 'astroid@exe/src_modes_forward_message.cc.o' 'astroid@exe/src_modes_editor_editor.cc.o' 'astroid@exe/src_modes_editor_external.cc.o' 'astroid@exe/src_modes_editor_plugin.cc.o' 'astroid@exe/src_modes_keybindings.cc.o' 'astroid@exe/src_modes_raw_message.cc.o' 'astroid@exe/src_modes_help_mode.cc.o' 'astroid@exe/src_actions_tag_action.cc.o' 'astroid@exe/src_actions_cmdaction.cc.o' 'astroid@exe/src_actions_onmessage.cc.o' 'astroid@exe/src_actions_action_manager.cc.o' 'astroid@exe/src_actions_difftag_action.cc.o' 'astroid@exe/src_actions_toggle_action.cc.o' 'astroid@exe/src_actions_action.cc.o' 'astroid@exe/src_astroid.cc.o' 'astroid@exe/src_db.cc.o' 'astroid@exe/src_config.cc.o' 'astroid@exe/src_poll.cc.o' 'astroid@exe/src_message_thread.cc.o' 'astroid@exe/src_utils_resource.cc.o' 'astroid@exe/src_utils_address.cc.o' 'astroid@exe/src_utils_gmime_gmime-compat.cc.o' 'astroid@exe/src_utils_gravatar.cc.o' 'astroid@exe/src_utils_date_utils.cc.o' 'astroid@exe/src_utils_ustring_utils.cc.o' 'astroid@exe/src_utils_cmd.cc.o' 'astroid@exe/src_utils_utils.cc.o' 'astroid@exe/src_utils_vector_utils.cc.o' 'astroid@exe/src_utils_gmime_gtrie.c.o' 'astroid@exe/src_utils_gmime_gmime-filter-html-bq.c.o' 'astroid@exe/src_utils_gmime_url-scanner.c.o' 'astroid@exe/src_crypto.cc.o' 'astroid@exe/src_account_manager.cc.o' 'astroid@exe/src_chunk.cc.o' 'astroid@exe/src_command_bar.cc.o' 'astroid@exe/src_compose_message.cc.o' 'astroid@exe/src_main_window.cc.o' 'astroid@exe/src_plugin_manager.cc.o' 'astroid@exe/src_plugin_astroid_activatable.c.o' 'astroid@exe/src_plugin_thread_view_activatable.c.o' 'astroid@exe/src_plugin_thread_index_activatable.c.o' 'astroid@exe/src_main.cc.o' -Wl,--no-undefined -Wl,--as-needed -pthread -Wl,--start-group -lgmime-2.6 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -Wl,--end-group -lboost_thread -lboost_filesystem -lboost_log_setup -lboost_log -lboost_date_time -lboost_system -lboost_program_options -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lgtkmm-3.0 -latkmm-1.6 -lgdkmm-3.0 -lgiomm-2.4 -lpangomm-1.4 -lglibmm-2.4 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lgio-2.0 -lcairomm-1.0 -lcairo -lsigc-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lwebkitgtk-3.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -ljavascriptcoregtk-3.0 -lglib-2.0 -lnotmuch -lvte-2.91 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lz -lpcre2-8 -lgnutls -lsass -lpeas-1.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgirepository-1.0 -lgobject-2.0 -lglib-2.0  
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_surface_get_width'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_egl_device_create'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_glx_device_create'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_surface_get_height'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_device_set_thread_aware'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_surface_create_for_texture'
collect2: error: ld returned 1 exit status
[72/95] Compiling C++ object 'test_open_db@exe/tests_test_open_db.cc.o'.
ninja: build stopped: subcommand failed.

```
any suggestions how to fix this?
tried to install this package from aur, got this error, tried to compile it by myself, but couldn't understand how to fix it.

**Comment by gauteh** [comment] 2017-10-13 14:06
Duplicate of: https://github.com/astroidmail/astroid/issues/406#issuecomment-331890010, please re-compile or install webkitgtk (pre-compiled packages here: https://github.com/astroidmail/astroid/wiki/Arch-Linux)

**Closed by gauteh** 2017-10-13 14:06 UTC

**Comment by seniorivn** [comment] 2017-10-13 14:16
@gauteh thanks, sorry for the duplicate
