### ISSUE TITLE
attachement does not display 

### ISSUE THREAD

**Issue by matclab** [astroidmail/astroid#504] opened 2018-05-25 11:34 UTC
When selecting a PDF attached to a mail and pressing <ENTER>, nothings happen.
The log is
```
[13:25:17.628435] [0x00007f726ec60a00] [info] chunk: CV.pdf, opening..
[13:25:17.628533] [0x00007f726ec60a00] [debug] chunk: saving to tmp path: /home/clabaut/.cache/astroid/v16x4c3cxn-CV.pdf
[13:25:17.628562] [0x00007f726ec60a00] [info] chunk: saving to: "/home/clabaut/.cache/astroid/v16x4c3cxn-CV.pdf"
[13:25:17.629325] [0x00007f726ec60a00] [info] chunk: contents: loaded 159005 bytes in 0.669 ms.
[13:25:17.629671] [0x00007f726ec60a00] [debug] tv: element action emitted: 2, action: enter
[13:25:17.629710] [0x00007f71d1de4700] [debug] chunk: spawning: xdg-open, /home/clabaut/.cache/astroid/v16x4c3cxn-CV.pdf
[13:25:17.775852] [0x00007f71d1de4700] [info] chunk: deleting tmp file: /home/clabaut/.cache/astroid/v16x4c3cxn-CV.pdf
```
If i save the attachment as /tmp/x.pdf, `xdg-open /tmp/x.pdf` works well.

I'm afraid the attachment is deleted before xdg-open had the time to manage it (on this computer, xdg-open is a script inspired from mimi: https://github.com/taylorchu/mimi)

**Comment by matclab** [comment] 2018-05-25 11:52
A hack is to add a `sleep 1` at the end of the xdg-open script.

I don't know if we do want astroid to store the temp file in a location that is either cleaned by astroid upon exiting or/and eventually will be cleaned by the system (like /tmp/xxx).

**Comment by gauteh** [comment] 2018-05-25 12:46
Does this solution work for you?


https://github.com/astroidmail/astroid/wiki/Opening-attachments-and-virus-detection

Skip virus check if you want.

- Gaute


fre. 25. mai 2018 kl. 13:52 skrev matclab <notifications@github.com>:

**Comment by gauteh** [comment] 2018-05-27 07:18
Closing. This is caused by vieweing-applications forking before having read the file. There is no reliable way for astroid to know when to delete the tmp file. /tmp should also be cleaned up on many systems, and a user specfic tmp directory is better for privacy on multi-user systems. A viewing application may continue to use the file even after astroid is exited, and may still use it when astroid is restarted. Which means that we can't clean the file on exit, and we can't clean the dir on re-start. I think the [inotify-watch method described in the wiki](https://github.com/astroidmail/astroid/wiki/Opening-attachments-and-virus-detection) is the best option for now.

**Closed by gauteh** 2018-05-27 07:18 UTC
Labels: question
