### ISSUE TITLE
Allow preferred mime content type to be configurable.

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [astroidmail/astroid#484] opened 2018-03-22 18:22 UTC
I couldn't see any way to set `html` as default other than changing the following line.

https://github.com/astroidmail/astroid/blob/875f3c5187abb071e2f2270418f3c2767d2566b3/src/chunk.hh#L50-L55

**Comment by gauteh** [comment] 2018-03-22 19:16
Duplicate of #236, currently not possible any other way.

**Closed by gauteh** 2018-03-22 19:16 UTC
Labels: duplicate
