### ISSUE TITLE
Crashed when sending mail

### ISSUE THREAD

**Issue by matclab** [astroidmail/astroid#575] opened 2018-10-12 13:27 UTC
Astroid crashes when sending a mail:
```
Process 24897 (astroid) of user 1000 dumped core.

Stack trace of thread 24954:
#0  0x00007eff76eb4d7f raise (libc.so.6)
#1  0x00007eff76e9f672 abort (libc.so.6)
#2  0x00007eff76c696d2 n/a (libtalloc.so.2)
#3  0x00007eff76c69ac2 n/a (libtalloc.so.2)
#4  0x00007eff7eab07e6 n/a (libnotmuch.so.5)
#5  0x00007eff7eac30a3 notmuch_thread_get_tags (libnotmuch.so.5)
#6  0x0000561fe232ca99 _ZN7Astroid13NotmuchThread8get_tagsEP15_notmuch_thread (astroid)
#7  0x0000561fe232cd83 _ZN7Astroid13NotmuchThread4loadEP15_notmuch_thread (astroid)
#8  0x0000561fe232d1d8 _ZN7Astroid13NotmuchThreadC1EP15_notmuch_thread (astroid)
#9  0x0000561fe2457546 _ZN7Astroid11QueryLoader6loaderEv (astroid)
#10 0x00007eff7729c063 execute_native_thread_routine (libstdc++.so.6)
#11 0x00007eff7789fa9d start_thread (libpthread.so.0)
#12 0x00007eff76f78a43 __clone (libc.so.6)

Stack trace of thread 24899:
#0  0x00007eff76f6dbb1 __poll (libc.so.6)
#1  0x00007eff79ecfee0 n/a (libglib-2.0.so.0)
#2  0x00007eff79ecffce g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007eff79ed0022 n/a (libglib-2.0.so.0)
#4  0x00007eff79e993eb n/a (libglib-2.0.so.0)
#5  0x00007eff7789fa9d start_thread (libpthread.so.0)
#6  0x00007eff76f78a43 __clone (libc.so.6)

Stack trace of thread 24897:
#0  0x00007eff76f6dbb1 __poll (libc.so.6)
#1  0x00007eff79ecfee0 n/a (libglib-2.0.so.0)
#2  0x00007eff79ecffce g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007eff7b2a17ee g_application_run (libgio-2.0.so.0)
#4  0x0000561fe22fe1db _ZN7Astroid7Astroid3runEiPPc (astroid)
#5  0x0000561fe22f7596 main (astroid)
#6  0x00007eff76ea1223 __libc_start_main (libc.so.6)
#7  0x0000561fe22f84ae _start (astroid)

Stack trace of thread 24900:
#0  0x00007eff76f6dbb1 __poll (libc.so.6)
#1  0x00007eff79ecfee0 n/a (libglib-2.0.so.0)
#2  0x00007eff79ed0f62 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007eff7b262c28 n/a (libgio-2.0.so.0)
#4  0x00007eff79e993eb n/a (libglib-2.0.so.0)
#5  0x00007eff7789fa9d start_thread (libpthread.so.0)
#6  0x00007eff76f78a43 __clone (libc.so.6)

Stack trace of thread 24974:
#0  0x00007eff778a5afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007eff77295cd1 __gthread_cond_wait (libstdc++.so.6)
#2  0x00007eff7af6056e _ZN7bmalloc9Scavenger13threadRunLoopEv (libjavascriptcoregtk-4.0.so.18)
#3  0x0100000000000000 n/a (n/a)

```

This is astroid! - 0.14.0 on arch linux.

The bad think is that my (long) email is lost. 
I can not find trace of it neither in /tmp, neither in ~/.cache/astroid, neither as a draft mail and neither in sent mail.
It would perhaps be nice that the mail is first labelled as a draft, and only when the sending is successful, moved to the `sent` label…

**Comment by matclab** [comment] 2018-10-12 13:33
The mail was nonetheless sent successfully (good news), AND it is indeed in the `sent` label. So the problem is not so bad.

**Comment by gauteh** [comment] 2018-10-12 13:37
Ah good, normally the cache is not deleted before after sending so if a
crash happens before the send command successfully completes it should not
be deleted.

**Comment by gauteh** [comment] 2018-10-17 09:00
This seems like it might be caused by external modification to the DB. Do you have an external poll script running (outside that from astroid)?

**Comment by gauteh** [comment] 2018-10-17 09:38
matclab writes on October 17, 2018 11:23:
> I have an external poll script but it is normally launched only if astroid is not running.
> 
> Perhaps we should put this issue on standby and I will comment here if I manage to reproduce the crash.

Ok, closing for now.

**Closed by gauteh** 2018-10-17 09:38 UTC
