### ISSUE TITLE
Allow search over keybindings tab

### ISSUE THREAD

**Issue by manishrjain** [astroidmail/astroid#400] opened 2017-09-09 08:19 UTC
Using `?` to open keybindings opens up a keybindings tab. This tab has a lot of information, which is hard to browse. Particularly because astroid doesn't allow any search over that tab. So, two things:

- Allow search over contents of this tab.
- Better organize this information by creating more sections by grouping related actions.

**Comment by mxmehl** [comment] 2017-09-09 09:58
Good idea.
Related to #208

**Comment by gauteh** [comment] 2017-09-13 13:59
Duplicate of #208.

**Closed by gauteh** 2017-09-13 13:59 UTC
