### ISSUE TITLE
Attachments can't be viewed when composing message

### ISSUE THREAD

**Issue by larskotthoff** [astroidmail/astroid#586] opened 2018-10-26 19:07 UTC
When attaching things while composing a message, the attachments show up and can be selected as usual. However, when pressing <Enter> to open them, the editor launches as the key binding for that is the same.

**Comment by gauteh** [comment] 2018-10-27 07:31
Lars Kotthoff writes on October 26, 2018 21:07:
> When attaching things while composing a message, the attachments show up and can be selected as usual. However, when pressing <Enter> to open them, the editor launches as the key binding for that is the same.

I think this is actually a duplicate of #584. Ctrl-space used to be an 
alternative keybinding. But somehow it stopped working during the 
migration to webkit2 (maybe webkit swallows it?). If you add an 
simple keybinding to that target (`thread_view.activate`), e.g.: `o`, 
you should be able to use that to open attachments and also open 
alternative parts.

**Comment by larskotthoff** [comment] 2018-10-27 19:50
Ok, thanks. Another alternative would be to check whether an attachment is focused when enter is pressed; or allow to open it by mouse click.

**Comment by gauteh** [comment] 2018-10-28 06:49
True, but I think it would be better to maybe change the keybinding for editing. Lets move the rest of the discussion to #584.

**Closed by gauteh** 2018-10-28 06:49 UTC
